## clean docker
# sudo docker system prune -a  
## install new versions
# cd /volume1/docker
# sudo docker-compose up -d

---
version: "2"
services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent1
    environment:
      - PUID=1033
      - PGID=100
      - TZ=Europe/Minsk
      - WEBUI_PORT=6004
    volumes:
      - /volume1/docker/qbittorrent:/config
      - /volume1/video/torrent:/video/torrent
    ports:
      - 6882:6882
      - 6882:6882/udp
      - 6004:6004
    restart: unless-stopped
    network_mode: "bridge"

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett1
    environment:
      - PUID=1033
      - PGID=100
      - TZ=Europe/Minsk
    volumes:
      - /volume1/docker/jackett:/config
      - /volume1/video/torrent:/video/torrent
    ports:
      - 6002:9117
    restart: unless-stopped
    network_mode: "bridge"

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr1
    environment:
      - PUID=1029
      - PGID=100
      - TZ=Europe/Minsk
    volumes:
      - /volume1/docker/radarr:/config
      - /volume1/video:/video
    ports:
      - 6003:7878
    restart: unless-stopped
    network_mode: "bridge"

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr1
    environment:
      - PUID=1029
      - PGID=100
      - TZ=Europe/Minsk
    volumes:
      - /volume1/docker/sonarr:/config
      - /volume1/video:/video
    ports:
      - 6005:8989
    restart: unless-stopped
    network_mode: "bridge"

  minidlna:
    image: vladgh/minidlna
    container_name: minidlna1
    environment:
      - PUID=1029
      - PGID=100
      - TZ=Europe/Minsk
      - MINIDLNA_MEDIA_DIR=/media
    volumes:
      - /volume1/docker/minidlna:/config
      - /volume1/video:/media
    # ports:
    #   - 6005:8989
    restart: unless-stopped
    network_mode: "host"


  bitwarden:
    image: vaultwarden/server:latest
    container_name: bitwarden1
    environment:
      - PUID=1029
      - PGID=100
      - TZ=Europe/Minsk
    volumes:
      - /volume1/docker/bitwarden:/data
    ports:
      - 3012:3012
      - 5151:80      
    restart: unless-stopped
    network_mode: "bridge"
